### ISSUE TITLE
MarkerClusterer 이용 중 문의가 있습니다

### ISSUE THREAD

**Issue by chazepps** [Musma/react-kakao-maps#4]
아주 잘 사용하고 있습니다 👍 

`MarkerClusterer`를 이용하려하는데, `MarkerClusterer`의 `options.markers`에 어떤 항목이 들어가야 하는지 궁금합니다~ 혹시 예제가 있으면 공유를 부탁드릴 수 있을까요?

![image](https://user-images.githubusercontent.com/1797699/73646906-bf45b000-46bd-11ea-95ce-7c514ad7839e.png)

**Comment by civilizeddev** [comment]
@ChazEpps
안녕하세요? 죄송합니다. 알림을 못봐서 답변을 못 드렸습니다.

```
<MarkerCluster options={{
  ...,
  markers=[
    <Marker options={...} />,
    <Marker options={...} />,
  ]
}} />
```

이렇게 사용해도 되고,

```
<MarkerCluster options={{ ... }}>
  <Marker options={...} />,
  <Marker options={...} />,
/MarkerCluster>
```

이렇게 사용해도 되는 것입니다.

감사합니다.

**Comment by chazepps** [comment]
고맙습니다 👍

**Comment by chazepps** [comment]
@civilizeddev 혹시 말씀하신 `MarkerCluster`가 아래 클래스가 맞나요?
![image](https://user-images.githubusercontent.com/1797699/75638899-92ab9680-5c71-11ea-913f-f913fb71f197.png)

`markers`의 type이 `Marker`가 아닌 듯 합니다 😅 

![image](https://user-images.githubusercontent.com/1797699/75638930-a820c080-5c71-11ea-9596-f5ed60430845.png)

**Comment by chazepps** [comment]
아래 방법으로 동작 확인했습니다.

![image](https://user-images.githubusercontent.com/1797699/75639426-11a1ce80-5c74-11ea-8fdc-010426389a6c.png)
